### ISSUE TITLE
[BUG] Migration check is not correct

### ISSUE THREAD

**Issue by allardy** [botpress/nlu#109]
The migration is missing a check to see if it need to run or not. I always use TESTMIG_NEW=true and AUTO_MIGRATE=true when developing and my config is overwritten everytime I reboot the server in botpress.config.json.

If the `nlu` key is already configured in botpress.config.json, the migration should be skipped

**Comment by franklevasseur** [comment]
Hi @allardy,

This issue is unrelated to NLU-server. Please open issues on the correct repo in the future.

Also, this only affects branch [next](https://github.com/botpress/botpress/tree/next) of Botpress so it's not released yet. For this reason, it should not be treated as a Github issue.

I'll close the issue for the reasons mentioned above.
