### ISSUE TITLE
[BUG] NLU should wait for language server

### ISSUE THREAD

**Issue by poojapatil12** [botpress/nlu#64]
**Describe the bug**
When starting Botpress with multiple languages, the languages server needs to finish loading and only then botpress can be started. Currently, there is no check to make sure lang server is running after which BP can start, as a result it crashes with

`Launcher Could not load Language Provider at http://localhost:3100: ETIMEDOUT`

although In nlu.json , "autoStart": true:

```
{
  "$schema": "../../assets/modules/nlu/config.schema.json",
  "nluServer": {
    "autoStart": true,
      "endpoint": http://localhost:3200
  },

```

**Expected behavior**
There should be some check which should not allow Botpress to attempt to start unless the lang servers are running

**Environment (please complete the following information):**

OS: macOS
Browser Chrome
Browser Version 91
Botpress Version 12.22.2
NodeJS v12.23.0

**Comment by hacheybj** [comment]
Duplicate: https://github.com/botpress/botpress/issues/4537

**Comment by franklevasseur** [comment]
Hi, sorry for the delay.

As @hacheybj said, this is a known issue and has already been flagged.

Unfortunately, this problem is not related to the NLU server itself, but rather to the way Botpress communicates with it. For this reason, this issue should be raised on the main Botpress Repo.

Thanks for you contribution,

François
